// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	_ "embed"
)

// Injectors from wire.go:

func BuildOutPipeline(root string, args OutCmd) (*OutPipeline, error) {
	directoryTree, err := ProvideDirectoryTreeService(root)
	if err != nil {
		return nil, err
	}
	v, err := ProvideFSList(root)
	if err != nil {
		return nil, err
	}
	resolver := ProvideResolver(v)
	counter, err := ProvideCounter(args)
	if err != nil {
		return nil, err
	}
	outputMetrics := ProvideMetrics(counter)
	renderer := ProvideRenderer(resolver, outputMetrics)
	fileMapWriter := ProvideFileMapService(root, outputMetrics)
	workingDirectory := ProvideWorkingDirectory(root)
	contentLoader := ProvideContentLoader()
	outPipeline := &OutPipeline{
		DT:               directoryTree,
		Renderer:         renderer,
		FileMap:          fileMapWriter,
		Metrics:          outputMetrics,
		Loader:           contentLoader,
		WorkingDirectory: workingDirectory,
		Template:         nil,
		ContentSpecs:     nil,
		DataPairs:        nil,
	}
	return outPipeline, nil
}
