// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	_ "embed"
)

// Injectors from wire.go:

func BuildOutPipeline(root string, args OutCmd) (*OutPipeline, error) {
	appEnv, err := ProvideAppEnv(root, args)
	if err != nil {
		return nil, err
	}
	directoryTree, err := ProvideDirectoryTreeService(appEnv)
	if err != nil {
		return nil, err
	}
	v, err := ProvideFSList(appEnv)
	if err != nil {
		return nil, err
	}
	resolver := ProvideResolver(appEnv, v)
	counter, err := ProvideCounter(args)
	if err != nil {
		return nil, err
	}
	outputMetrics := ProvideMetrics(counter)
	renderer := ProvideRenderer(resolver, outputMetrics)
	fs, err := ProvideRootFS(appEnv)
	if err != nil {
		return nil, err
	}
	fileMapWriter := ProvideFileMapService(appEnv, fs, outputMetrics)
	contentLoader := ProvideContentLoader()
	template, err := ProvideTemplate(appEnv, resolver, args, v)
	if err != nil {
		return nil, err
	}
	outPipeline := &OutPipeline{
		DT:       directoryTree,
		Renderer: renderer,
		FileMap:  fileMapWriter,
		Metrics:  outputMetrics,
		Loader:   contentLoader,
		Env:      appEnv,
		Template: template,
	}
	return outPipeline, nil
}
