// Code generated by wire. DO NOT EDIT.
//go:build !wireinject

package main

func BuildOutPipeline(root string, args OutCmd) (*OutPipeline, error) {
    counter, err := ProvideCounter(args)
    if err != nil {
        return nil, err
    }
    metrics := ProvideMetrics(counter)
    fsList, err := ProvideFSList(root)
    if err != nil {
        return nil, err
    }
    resolver := ProvideResolver(fsList)
    renderer := ProvideRenderer(resolver, metrics)
    dt, err := ProvideDirectoryTreeService(root)
    if err != nil {
        return nil, err
    }
    fileMap := ProvideFileMapService(root, metrics)
    loader := ProvideContentLoader()
    pipe := &OutPipeline{
        DT:       dt,
        Renderer: renderer,
        FileMap:  fileMap,
        Metrics:  metrics,
        Loader:   loader,
    }
    return pipe, nil
}
